oceanbase/docker-images

.github/workflow/release-oceanbase-cloud-native.yml
oceanbase-cloud-native/Dockerfile

Add dockerfile and workflow to build oceanbase-cloud-native image

Oceanbase cloud native

---

.github/workflows/ci-oceanbase-ce.yml
oceanbase-ce/docker_build.sh

build: add oceanbase-ce CI workflow

---

.github/workflows/release-obproxy-ce.yml
.github/workflows/release-oceanbase-cloud-native.yml

1. Added workflow for releasing obproxy-ce
2. Fixed Dockerfile reference path in `release-oceanbase-cloud-native.yml`

Fixed workflows for releasing oceanbase-cloud-native and obproxy-ce

---

.github/workflows/release-ob-configserver.yml
.github/workflows/release-obagent.yml
.github/workflows/release-obproxy-ce.yml
.github/workflows/release-oceanbase-cloud-native.yml
.github/workflows/test-oceanbase-ce.yml

1. Update actions to suppress warnings
2. Change tag for releasing obproxy from `obproxy-` to `obproxy-ce-`
3. Rename oceanbase-ci to 'test oceanbase-ce'

chore: update used actions and modify test ci name

---

.github/workflows/release-oblogproxy-ce.yml
oblogproxy-ce/Dockerfile
oblogproxy-ce/start.sh

feat: add a workflow for publishing oblogproxy-ce

---

oceanbase-ce/Dockerfile

add build platform

---

.github/workflows/build-oceanbase-ce.yml
.github/workflows/test-oceanbase-ce.yml

extract reusable workflow build-oceanbase-ce

---

ob-configserver/Dockerfile
ob-configserver/env.sh
ob-configserver/start.sh

add default values for ob-configserver

add default values for ob-configserver

---

.github/workflows/release-lts-oceanbase-ce.yml
.github/workflows/release-ob-configserver.yml
.github/workflows/release-obagent.yml
.github/workflows/release-oblogproxy-ce.yml
.github/workflows/release-obproxy-ce.yml
.github/workflows/release-oceanbase-ce.yml
.github/workflows/release-oceanbase-cloud-native.yml

1. config workflows to push images to dockerhub, quay.io and ghcr.io
2. change workflow trigger condition to build lts version images, triggered with tag starts with lts-oceanbase, and it will update the image with tag 'latest'
3. use concrete version of oceanbase package as tag

Push images

---

.github/workflows/release-lts-oceanbase-ce.yml

upload image with tag x.x.x-lts when run release-lts-oceanbase workflow

set lts tag

---

.github/workflows/test-oblogproxy-ce.yml
.github/workflows/test-oceanbase-ce.yml
oblogproxy-ce/start.sh
test/pom.xml
test/src/test/java/com/oceanbase/test/LogProxyCETest.java
test/src/test/java/com/oceanbase/test/Utils.java

add java test case for oblogproxy-ce

---

oblogproxy-ce/README.md

add README.md for oblogproxy-ce

---

.github/workflows/release-latest-oblogproxy-ce.yml
.github/workflows/test-oblogproxy-ce.yml
.github/workflows/test-oceanbase-ce.yml

add release workflow for latest oblogproxy-ce

---

.github/workflows/release-obdiag-builder.yml
obdiag-builder/Dockerfile

Add obdiag base

---

oceanbase-ce/Dockerfile

fix: remove incorrectly used platform option in oceanbase-ce image

---

.github/workflows/release-lts-oceanbase-ce.yml
.github/workflows/release-oceanbase-ce.yml
.github/workflows/release-oceanbase-cloud-native.yml

support multiple conditions to publish oceanbase images

support publish oceanbase image seperately

---

oceanbase-ce/README_CN.md

add readme in Chinese

---

obagent/Dockerfile
obagent/conf/monitor_ob.yaml
obagent/replace_properties.sh

1. package obagent using customized collect config
2. support set host ip using environment variable

enhance obagent

---

oceanbase-ce/Dockerfile
oceanbase-ce/boot/start.sh
oceanbase-ce/templates/observer-template.yaml

1. generate random oceanbase cluster id
2. fix dependency problems when installing dependencies
3. use subdirectory under /root/ob to avoid mount problem

Optimize oceanbase ce image

---

.github/workflows/release-latest-lts-oceanbase-ce.yml
.github/workflows/release-oceanbase-ce.yml
.github/workflows/release-oceanbase-cloud-native.yml
.github/workflows/reusable-build-and-release-oceanbase-ce.yml
.github/workflows/reusable-build-and-test-oceanbase-ce.yml
.github/workflows/reusable-test-and-release-oceanbase-ce.yml

using tag starting with latest-lts to trigger workflow pushing image with latest tag
tag starting with lts will only pushing image with x.x.x-lts

Optimize oceanbase ce workflow
